// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CentroidData struct {
	FreqCentroidHz float64 `json:"freq_centroid_Hz"`
	TimeCentroidNs float64 `json:"time_centroid_ns"`
}

type CentroidPayload struct {
	AcquiredAt              string          `json:"acquired_at"`
	AcquisitionID           string          `json:"acquisition_id"`
	Centroid                []*CentroidData `json:"centroid"`
	CentroidProcessDuration float64         `json:"centroidProcessDuration"`
	Error                   string          `json:"error"`
	SensorID                string          `json:"sensor_id"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
